<div id="content">
	<h1>Paramore</h1>
		<img src="../images/paramore.png" class="bandPic" alt="Paramore">

		Influenced by the sugar-coated emo and mainstream pop-punk of Jimmy Eat World and Avril Lavigne, the (mostly teenage) lineup of the Tennessee-based Paramore found success when their second album Riot! (Number 15, 2007) produced hits in the lurching "Crushcrushcrush" (Number Four Modern Rock; Number 54 Pop, 2007) and nimble "Misery Business" (Number Three Modern Rock; Number 26 Pop, 2007).
	<p><br>
		Paramore formed in Franklin, Tennessee, after guitarist Josh Farro and his brother Zac met Mississippi transplant Hayley Williams at the private school they all attended and broadened their new friend's musical horizons. Adding bassist Jeremy Davis and rhythm guitarist Jason Bynum, the band played its first gigs in early 2004. Within six months they were signed to Florida-based indie label Fueled by Ramen, home of Jimmy Eat World and Fall Out Boy.
	<p><br>
		Paramore's 2005 debut All We Know Is Falling reached Number 30 on Billboard's Heatseekers chart and created a buzz and critical kudos for Williams' strong vocals and songwriting. In late 2005, Bynum was replaced by guitarist Hunter Lamb, who left the group in early 2007 (they carried on as a four-piece). The band's highly anticipated 2007 follow-up Riot! received generally favorable reviews and shot to the Top 20 on the strength of its two biggest singles and videos. The band was nominated for Best New Artist at the 2008 Grammy Awards. Though the group is Christian, they don't consider themselves to be a Christian-rock band and tend to keep their faith out of their songwriting and interviews.
	<p><br>
		As the band began to attract more and more media attention, speculation arose that they were suffering from a problem that plagued No Doubt in their early days, and Paramore began expressing displeasure with Williams being the focus of magazine articles. In early 2008, the band, which had experienced personnel shakeups from early on, pulled out of a U.K. and European tour supporting Riot! due to what it termed "internal issues." They went on to co-headline a set of arena dates with Jimmy Eat World and assured fans they were not breaking up in a series of interviews and candid blog posts. In summer 2008, the band embarked upon their fourth Warped Tour as well as a headlining trek of amphitheaters.

</div>