<div id="content">
	<h1>The Police</h1>
		<img src="../images/thepolice.png" class="bandPic" alt="The Police">

		The Police's songs are unmistakable. Both canny and cosmopolitan, the British trio's sound blended pop hooks and tricky rhythms. Reggae beats here, African funk there, and on top of all the pulsing grooves, the keening wail of Sting's voice. The band, driven by Stewart Copeland's drums, Andy Summers' guitar, and Sting's bass, leapt from the punk underground to conquer the radio airwaves with 1978's "Roxanne." For the next several years they went on to create a wildly successful body of work that was both experimental and highly pop-wise. Maybe that's why they titled their most popular album Synchronicity, and maybe that's why — 30 years after they arrived on the scene — their reunion tour was one of the most celebrated rock events of 2008.
	<p><br>
		Gordon Sumner, who got his nom de fame "Sting" because of a bee-like yellow and black jersey he wore as a young musician, had been a teacher, ditch digger, and civil servant while working with several jazz combos in Newcastle, England. It was in a British jazz club that he met American drummer Stewart Copeland. The son of a swing-loving CIA agent and an archaeologist with an appreciation for classical music, Copeland had grown up in the Middle East, attended college in California, moved to England in 1975, and joined the English progressive-rock group Curved Air. When that band broke up, Copeland formed the Police with Sting and guitarist Henri Padovani in 1977. After a few months of club dates, they replaced Padovani with Andy Summers, whose list of previous employers stretched Eric Burdon and the Animals to Neil Sedaka; a bit older than his new mates, he had also studied classical guitar in California.
	<p><br>
		Summers' post-Police career, while less varied, has been distinguished by adventurous rock, jazz, and fusion albums, both alone and in collaboration with such respected musicians as Fripp and British jazz guitarist John Etheridge. His 1999 solo release Green Chimneys: The Music of Thelonious Monk featured Sting on vocals of the track "Round Midnight." Also in 1999, Summers participated in a cross-cultural songwriting exchange workshop in Cuba. Twenty years after their 1986 split the band reunited for a world tour which had symbolic kick-off at the 2007 Grammys ceremonies. Henry Padovani even joined them during a Paris date later in the year. But longevity wasn't part of the plan. Sting told fans that once the tour was completed the band would never record or tour again, and on August 7, 2008 at Madison Square Garden, the trio gave its final performance, donating the proceeds to local NPR television stations. The trek was the third highest-grossing rock tour ever, taking in over $350 million dollars.

</div>